#机器人功能设置
Ver: "1.2.2"

#QQ群聊命令前缀
Prefix: "/"

#消息转发
Forwarding:
  enable: true
  mode: 0 #mode设为0即无条件转发消息，设为1则消息前有前缀才会转发消息
  prefix: "#"

#死亡报告
DieReport: false

#白名单
WhiteList:
  enable: false
  kickMsg: "请加入qq群:xxx申请白名单"

#执行命令功能
CMD: true

#进出提示
JoinAndLeave: true

#在线玩家查询
Online: true

#tps查询
TPS: true

#自定义命令
SDC: true

#自定义回复
SDR: true